import { BackgroundConfig } from "./types";

export const SOLID_PRESETS: BackgroundConfig[] = [
  { type: "solid", color: "#0a0a0a" },
  { type: "solid", color: "#111111" },
  { type: "solid", color: "#1a1a1a" },
  { type: "solid", color: "#1e1e1e" },
  { type: "solid", color: "#202020" },
  { type: "solid", color: "#2a2a2a" },
  { type: "solid", color: "#333333" },
  { type: "solid", color: "#404040" },
  { type: "solid", color: "#fafafa" },
  { type: "solid", color: "#f9f9f9" },
  { type: "solid", color: "#f5f5f5" },
  { type: "solid", color: "#f0f0f0" },
  { type: "solid", color: "#eaeaea" },
  { type: "solid", color: "#fefefe" },
  { type: "solid", color: "#ffffff" },
  { type: "solid", color: "#e5e5e5" },
  { type: "solid", color: "#f5f1ea" },
  { type: "solid", color: "#ede4d3" },
  { type: "solid", color: "#e8dcc4" },
  { type: "solid", color: "#d9c7a7" },
  { type: "solid", color: "#c9b79c" },
  { type: "solid", color: "#b8a082" },
  { type: "solid", color: "#f4f6f8" },
  { type: "solid", color: "#e2e8f0" },
  { type: "solid", color: "#cbd5e1" },
  { type: "solid", color: "#94a3b8" },
  { type: "solid", color: "#64748b" },
  { type: "solid", color: "#334155" },
  { type: "solid", color: "#fce7f3" },
  { type: "solid", color: "#fde68a" },
  { type: "solid", color: "#d1fae5" },
  { type: "solid", color: "#dbeafe" },
  { type: "solid", color: "#ede9fe" },
  { type: "solid", color: "#ffedd5" },
];

export const GRADIENT_PRESETS: BackgroundConfig[] = [
  { type: "gradient", colors: ["#0a0a0a", "#121212"] },
  { type: "gradient", colors: ["#121212", "#1a1a1a"] },
  { type: "gradient", colors: ["#151515", "#202020"] },
  { type: "gradient", colors: ["#1c1c1c", "#282828"] },
  { type: "gradient", colors: ["#202020", "#303030"] },
  { type: "gradient", colors: ["#000000", "#181818"] },
  { type: "gradient", colors: ["#141414", "#0f0f0f"] },
  { type: "gradient", colors: ["#181818", "#262626"] },
  { type: "gradient", colors: ["#18181b", "#27272a"] },
  { type: "gradient", colors: ["#27272a", "#3f3f46"] },
  { type: "gradient", colors: ["#fafafa", "#e4e4e7"] },
  { type: "gradient", colors: ["#f4f4f5", "#d4d4d8"] },
  { type: "gradient", colors: ["#ffffff", "#e0e0e0"] },
  { type: "gradient", colors: ["#262322", "#35302e"] },
  { type: "gradient", colors: ["#2d2926", "#3d3834"] },
  { type: "gradient", colors: ["#f5f4f0", "#e6e2da"] },
  { type: "gradient", colors: ["#eae5df", "#d8d1c7"] },
  { type: "gradient", colors: ["#f3efe6", "#e4ddd1"] },
  { type: "gradient", colors: ["#0d0e11", "#16181d"] },
  { type: "gradient", colors: ["#111318", "#1e222a"] },
  { type: "gradient", colors: ["#191b20", "#2c3038"] },
  { type: "gradient", colors: ["#0f1115", "#21252d"] },
  { type: "gradient", colors: ["#ffffff", "#f9f9f9"] },
  { type: "gradient", colors: ["#fcfcfc", "#f2f2f2"] },
  { type: "gradient", colors: ["#f5f5f5", "#ebebeb"] },
  { type: "gradient", colors: ["#fafafa", "#f0f0f0"] },
  { type: "gradient", colors: ["#ffffff", "#f4f4f5"] },
  { type: "gradient", colors: ["#fefefa", "#f5f3ef"] },
  { type: "gradient", colors: ["#faf8f5", "#eeeae3"] },
  { type: "gradient", colors: ["#fdfcfb", "#e9e5df"] },
  { type: "gradient", colors: ["#f8f9fa", "#e9ecef"] },
  { type: "gradient", colors: ["#f4f5f7", "#e2e8f0"] },
  { type: "gradient", colors: ["#ffffff", "#e4e4e7"] },
  { type: "gradient", colors: ["#09090b", "#18181b"] },
  { type: "gradient", colors: ["#111113", "#222226"] },
  { type: "gradient", colors: ["#18181b", "#27272a"] },
  { type: "gradient", colors: ["#141414", "#1e1e1e"] },
  { type: "gradient", colors: ["#fefefa", "#f2eae1"] },
  { type: "gradient", colors: ["#faf8f5", "#e8ded1"] },
  { type: "gradient", colors: ["#fdfcfb", "#e4dcd0"] },
  { type: "gradient", colors: ["#f5f1ea", "#e3d7c6"] },
  { type: "gradient", colors: ["#f9f6f0", "#ece5db"] },
  { type: "gradient", colors: ["#ffffff", "#f0ebe1"] },
  { type: "gradient", colors: ["#fcfaf7", "#e5ddd0"] },
  { type: "gradient", colors: ["#f4efe6", "#dad0c0"] },
  { type: "gradient", colors: ["#fefdfb", "#ebe3d8"] },
  { type: "gradient", colors: ["#faf6f0", "#dfd5c5"] },

];
