export interface TemplatePreset {
  id: number;
  name: string;
  badge: string;
  json: string;
}

export const TEMPLATES: TemplatePreset[] = [
  // ── 01. Cover: Editorial Studio (Журнальная обложка с плашкой-бейджем и акцентной типографикой) ──
  {
    id: 1,
    name: "Editorial Mockup Cover",
    badge: "Cover • 01",
    json: JSON.stringify({
      version: "5.3.0",
      background: "#f8f7f4",
      objects: [
        // Верхний лейбл-категория
        {
          type: "textbox",
          text: "DESIGN CURATION — ISSUE 04",
          left: 540,
          top: 70,
          originX: "center",
          fontSize: 13,
          fontWeight: "700",
          fontFamily: "monospace",
          charSpacing: 220,
          fill: "#8c877d",
          textAlign: "center",
        },
        // Фото 1: сверху слева (мокап футболки на камне)
        {
          type: "image",
          src: "https://images.unsplash.com/photo-1521572267360-ee0c2909d518?w=800&auto=format&fit=crop&q=85",
          crossOrigin: "anonymous",
          left: 70,
          top: 130,
          scaleX: 0.36,
          scaleY: 0.36,
          rx: 20,
          ry: 20,
          stroke: "rgba(0,0,0,0.06)",
          strokeWidth: 1,
          shadow: { color: "rgba(0,0,0,0.07)", blur: 24, offsetX: 0, offsetY: 12 },
        },
        // Фото 2: сверху справа (худи в ночном свете)
        {
          type: "image",
          src: "https://images.unsplash.com/photo-1509631179647-0177331693ae?w=800&auto=format&fit=crop&q=85",
          crossOrigin: "anonymous",
          left: 710,
          top: 110,
          scaleX: 0.36,
          scaleY: 0.36,
          rx: 20,
          ry: 20,
          stroke: "rgba(0,0,0,0.06)",
          strokeWidth: 1,
          shadow: { color: "rgba(0,0,0,0.07)", blur: 24, offsetX: 0, offsetY: 12 },
        },
        // Верхняя строка заголовка
        {
          type: "textbox",
          text: "Где я беру",
          left: 540,
          top: 420,
          originX: "center",
          originY: "center",
          fontSize: 78,
          fontWeight: "800",
          fontFamily: "Georgia, 'Playfair Display', serif",
          fill: "#141413",
          textAlign: "center",
          width: 780,
        },
        // Акцентная плашка-прямоугольник под главное слово
        {
          type: "rect",
          left: 540,
          top: 550,
          originX: "center",
          originY: "center",
          width: 490,
          height: 104,
          fill: "#141413",
          rx: 14,
          ry: 14,
          shadow: { color: "rgba(20,20,19,0.22)", blur: 32, offsetX: 0, offsetY: 16 },
        },
        // Текст внутри плашки (чистый современный гротеск)
        {
          type: "textbox",
          text: "мокапы?",
          left: 540,
          top: 550,
          originX: "center",
          originY: "center",
          fontSize: 74,
          fontWeight: "800",
          fontFamily: "Inter, -apple-system, sans-serif",
          fill: "#ffffff",
          textAlign: "center",
          charSpacing: 20,
        },
        // Фото 3: снизу по центру (кожаное кресло и экран)
        {
          type: "image",
          src: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=800&auto=format&fit=crop&q=85",
          crossOrigin: "anonymous",
          left: 170,
          top: 690,
          scaleX: 0.44,
          scaleY: 0.44,
          rx: 20,
          ry: 20,
          stroke: "rgba(0,0,0,0.06)",
          strokeWidth: 1,
          shadow: { color: "rgba(0,0,0,0.08)", blur: 28, offsetX: 0, offsetY: 14 },
        },
        // Подпись автора в правом нижнем углу
        {
          type: "textbox",
          text: "tg channel:\n@zavialoova",
          left: 1010,
          top: 960,
          originX: "right",
          originY: "bottom",
          fontSize: 22,
          lineHeight: 1.35,
          fontFamily: "Inter, sans-serif",
          fontWeight: "500",
          fill: "#2e2c29",
          textAlign: "right",
        },
      ],
    }),
  },

  // ── 02. Slide: Resource Showcase (Швейцарская модульная верстка с карточками и списком) ──
  {
    id: 2,
    name: "Resource Showcase Grid",
    badge: "Slide • 02",
    json: JSON.stringify({
      version: "5.3.0",
      background: "#ffffff",
      objects: [
        // Мягкая декоративная подложка под правую половину
        {
          type: "rect",
          left: 490,
          top: 0,
          width: 590,
          height: 1080,
          fill: "#faf9f6",
        },
        // Верхний номер раздела
        {
          type: "textbox",
          text: "{ 01 }",
          left: 80,
          top: 90,
          fontSize: 28,
          fontFamily: "monospace",
          fontWeight: "600",
          fill: "#9ca3af",
          charSpacing: 100,
        },
        // Копирайт автора сверху справа
        {
          type: "textbox",
          text: "tg: @zavialoova",
          left: 1000,
          top: 95,
          originX: "right",
          fontSize: 20,
          fontFamily: "Inter, sans-serif",
          fontWeight: "600",
          fill: "#71717a",
        },
        // Имя платформы / сервиса
        {
          type: "textbox",
          text: "freepik",
          left: 80,
          top: 170,
          fontSize: 90,
          fontWeight: "900",
          fontFamily: "Inter, sans-serif",
          charSpacing: -40,
          fill: "#09090b",
        },
        // Описание-слоган слева
        {
          type: "textbox",
          text: "Базовая библиотека,\nкоторой я пользуюсь\nбуквально каждый день.",
          left: 80,
          top: 320,
          fontSize: 28,
          lineHeight: 1.35,
          fontFamily: "Georgia, serif",
          fill: "#3f3f46",
          width: 370,
        },
        // Главная карточка с предметом (стул / дизайн-объект)
        {
          type: "image",
          src: "https://images.unsplash.com/photo-1581539250439-c96689b516dd?w=900&auto=format&fit=crop&q=85",
          crossOrigin: "anonymous",
          left: 540,
          top: 170,
          scaleX: 0.54,
          scaleY: 0.54,
          rx: 22,
          ry: 22,
          stroke: "rgba(0,0,0,0.06)",
          strokeWidth: 1,
          shadow: { color: "rgba(0,0,0,0.08)", blur: 30, offsetX: 0, offsetY: 15 },
        },
        // Вторая карточка снизу слева (книга / мокап)
        {
          type: "image",
          src: "https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&auto=format&fit=crop&q=85",
          crossOrigin: "anonymous",
          left: 80,
          top: 610,
          scaleX: 0.44,
          scaleY: 0.44,
          rx: 22,
          ry: 22,
          stroke: "rgba(0,0,0,0.06)",
          strokeWidth: 1,
          shadow: { color: "rgba(0,0,0,0.08)", blur: 30, offsetX: 0, offsetY: 15 },
        },
        // Акцентный блок-тезис справа
        {
          type: "textbox",
          text: "Огромный архив под любые задачи:\nот айдентики и мерча до упаковок и 3D-сцен.",
          left: 540,
          top: 650,
          fontSize: 26,
          lineHeight: 1.45,
          fontFamily: "Inter, sans-serif",
          fontWeight: "500",
          fill: "#18181b",
          width: 440,
        },
        // Сноска
        {
          type: "textbox",
          text: "✦  особенно спасает с премиум-подпиской",
          left: 540,
          top: 890,
          fontSize: 21,
          fontFamily: "Inter, sans-serif",
          fontWeight: "600",
          fill: "#a1a1aa",
        },
      ],
    }),
  },

  // ── 03. Moodboard / Architecture: Aesthetic Gallery (Премиальная галерея с бейджем-таблеткой) ──
  {
    id: 3,
    name: "Architectural Moodboard",
    badge: "Gallery • 03",
    json: JSON.stringify({
      version: "5.3.0",
      background: "#f4f3ef",
      objects: [
        // Аккуратная пилюля-категория
        {
          type: "rect",
          left: 80,
          top: 75,
          width: 170,
          height: 38,
          fill: "#ffffff",
          rx: 19,
          ry: 19,
          stroke: "rgba(0,0,0,0.06)",
          strokeWidth: 1,
        },
        {
          type: "textbox",
          text: "INSPIRATION",
          left: 165,
          top: 94,
          originX: "center",
          originY: "center",
          fontSize: 12,
          fontWeight: "800",
          fontFamily: "Inter, sans-serif",
          charSpacing: 180,
          fill: "#27272a",
          textAlign: "center",
        },
        // Заголовок в стиле арт-дирекции
        {
          type: "textbox",
          text: "Форма,\nсвет и текстура",
          left: 80,
          top: 150,
          fontSize: 68,
          fontWeight: "700",
          fontFamily: "Georgia, 'Playfair Display', serif",
          fill: "#18181b",
          lineHeight: 1.15,
        },
        // Вертикальное архитектурное фото справа (брутализм / теплый свет)
        {
          type: "image",
          src: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=900&auto=format&fit=crop&q=85",
          crossOrigin: "anonymous",
          left: 550,
          top: 75,
          scaleX: 0.54,
          scaleY: 0.54,
          rx: 24,
          ry: 24,
          stroke: "rgba(0,0,0,0.06)",
          strokeWidth: 1,
          shadow: { color: "rgba(0,0,0,0.09)", blur: 32, offsetX: 0, offsetY: 16 },
        },
        // Горизонтальное фото текстуры снизу слева
        {
          type: "image",
          src: "https://images.unsplash.com/photo-1618221195710-dd6b41faaea6?w=800&auto=format&fit=crop&q=85",
          crossOrigin: "anonymous",
          left: 80,
          top: 480,
          scaleX: 0.48,
          scaleY: 0.48,
          rx: 24,
          ry: 24,
          stroke: "rgba(0,0,0,0.06)",
          strokeWidth: 1,
          shadow: { color: "rgba(0,0,0,0.09)", blur: 32, offsetX: 0, offsetY: 16 },
        },
        // Текстовый вывод / мысль снизу справа
        {
          type: "textbox",
          text: "Качественные референсы определяют 80% успеха финального кейса. Подбираем глубину и геометрию.",
          left: 550,
          top: 820,
          fontSize: 23,
          lineHeight: 1.45,
          fontFamily: "Inter, sans-serif",
          fontWeight: "400",
          fill: "#52525b",
          width: 440,
        },
        // Нумерация слайда
        {
          type: "textbox",
          text: "SLIDE 03 / 10",
          left: 1000,
          top: 990,
          originX: "right",
          fontSize: 14,
          fontFamily: "monospace",
          fontWeight: "700",
          charSpacing: 150,
          fill: "#a1a1aa",
        },
      ],
    }),
  },
];
