export interface SolidPreset {
  type: "solid";
  color: string;
}

export interface GradientPreset {
  type: "gradient";
  colors: [string, string];
}

export interface SuggestedSet {
  id: string;
  label: string;
  background: string;
  text: string;
  accent: string;
  card: string;
}

/** Neutrals plus the warmer and clearer colors showing up in 2026 carousels. */
export const SOLID_PRESETS: SolidPreset[] = [
  { type: "solid", color: "#000000" },
  { type: "solid", color: "#0a0a0a" },
  { type: "solid", color: "#111111" },
  { type: "solid", color: "#121212" },
  { type: "solid", color: "#1a1a1a" },
  { type: "solid", color: "#252525" },
  { type: "solid", color: "#303030" },
  { type: "solid", color: "#3d3d3d" },
  { type: "solid", color: "#4a4a4a" },
  { type: "solid", color: "#5a5a5a" },
  { type: "solid", color: "#6b6b6b" },
  { type: "solid", color: "#808080" },
  { type: "solid", color: "#999999" },
  { type: "solid", color: "#b0b0b0" },
  { type: "solid", color: "#c4c4c4" },
  { type: "solid", color: "#d4d4d4" },
  { type: "solid", color: "#e0e0e0" },
  { type: "solid", color: "#e8e8e8" },
  { type: "solid", color: "#f0f0f0" },
  { type: "solid", color: "#f1f1f1" },
  { type: "solid", color: "#f5f5f5" },
  { type: "solid", color: "#f9f9f9" },
  { type: "solid", color: "#ffffff" },
  { type: "solid", color: "#F7F1E5" },
  { type: "solid", color: "#F6E27A" },
  { type: "solid", color: "#F4A261" },
  { type: "solid", color: "#E7D3C0" },
  { type: "solid", color: "#C46B4A" },
  { type: "solid", color: "#A47864" },
  { type: "solid", color: "#D7263D" },
  { type: "solid", color: "#F3D1C8" },
  { type: "solid", color: "#7D9B76" },
  { type: "solid", color: "#5C6B3A" },
  { type: "solid", color: "#1F7A6B" },
  { type: "solid", color: "#7FDBDA" },
  { type: "solid", color: "#2F5DFF" },
  { type: "solid", color: "#1C2B4A" },
  { type: "solid", color: "#CDB4DB" },
  { type: "solid", color: "#6C4AB6" },
];

export const GRADIENT_PRESETS: GradientPreset[] = [
  { type: "gradient", colors: ["#000000", "#121212"] },
  { type: "gradient", colors: ["#0a0a0a", "#1a1a1a"] },
  { type: "gradient", colors: ["#111111", "#252525"] },
  { type: "gradient", colors: ["#121212", "#2a2a2a"] },
  { type: "gradient", colors: ["#1a1a1a", "#333333"] },
  { type: "gradient", colors: ["#252525", "#3a3a3a"] },
  { type: "gradient", colors: ["#2a2a2a", "#404040"] },
  { type: "gradient", colors: ["#333333", "#4a4a4a"] },
  { type: "gradient", colors: ["#ffffff", "#f1f1f1"] },
  { type: "gradient", colors: ["#fafafa", "#e8e8e8"] },
  { type: "gradient", colors: ["#f9f9f9", "#e0e0e0"] },
  { type: "gradient", colors: ["#f5f5f5", "#d4d4d4"] },
  { type: "gradient", colors: ["#ffffff", "#d9d9d9"] },
  { type: "gradient", colors: ["#f1f1f1", "#c8c8c8"] },
  { type: "gradient", colors: ["#e5e5e5", "#ffffff"] },
  { type: "gradient", colors: ["#181818", "#303030"] },
  { type: "gradient", colors: ["#F6E27A", "#F7F1E5"] },
  { type: "gradient", colors: ["#F4A261", "#F3D1C8"] },
  { type: "gradient", colors: ["#1F7A6B", "#1C2B4A"] },
  { type: "gradient", colors: ["#2F5DFF", "#CDB4DB"] },
  { type: "gradient", colors: ["#7D9B76", "#F7F1E5"] },
  { type: "gradient", colors: ["#D7263D", "#A47864"] },
  { type: "gradient", colors: ["#7FDBDA", "#F6E27A"] },
  { type: "gradient", colors: ["#6C4AB6", "#1C2B4A"] },
];

/** Carousel sets: the neutral range, then the 2026 color stories. */
export const SUGGESTED_SETS: SuggestedSet[] = [
  {
    id: "white",
    label: "White",
    background: "#ffffff",
    text: "#121212",
    accent: "#3a3a3a",
    card: "#f5f5f5",
  },
  {
    id: "paper",
    label: "Paper",
    background: "#f9f9f9",
    text: "#1a1a1a",
    accent: "#454545",
    card: "#ffffff",
  },
  {
    id: "mist",
    label: "Mist",
    background: "#f1f1f1",
    text: "#171717",
    accent: "#333333",
    card: "#fafafa",
  },
  {
    id: "stone",
    label: "Stone",
    background: "#e5e5e5",
    text: "#111111",
    accent: "#2a2a2a",
    card: "#f7f7f7",
  },
  {
    id: "graphite",
    label: "Graphite",
    background: "#252525",
    text: "#f1f1f1",
    accent: "#d4d4d4",
    card: "#333333",
  },
  {
    id: "ink",
    label: "Ink",
    background: "#121212",
    text: "#f5f5f5",
    accent: "#c8c8c8",
    card: "#1e1e1e",
  },
  {
    id: "charcoal",
    label: "Charcoal",
    background: "#1a1a1a",
    text: "#eeeeee",
    accent: "#bdbdbd",
    card: "#2c2c2c",
  },
  {
    id: "black",
    label: "Black",
    background: "#000000",
    text: "#fafafa",
    accent: "#e5e5e5",
    card: "#141414",
  },
  {
    id: "butter",
    label: "Butter",
    background: "#F7F1E5",
    text: "#1C2B4A",
    accent: "#E3B505",
    card: "#FFFFFF",
  },
  {
    id: "clay",
    label: "Clay",
    background: "#F6EDE6",
    text: "#3D2418",
    accent: "#C46B4A",
    card: "#FFFFFF",
  },
  {
    id: "cherry",
    label: "Cherry",
    background: "#F8F1F1",
    text: "#1A1214",
    accent: "#D7263D",
    card: "#FFFFFF",
  },
  {
    id: "sage",
    label: "Sage",
    background: "#F3F5EF",
    text: "#1E2A1C",
    accent: "#5C6B3A",
    card: "#FFFFFF",
  },
  {
    id: "teal",
    label: "Teal",
    background: "#F2F7F6",
    text: "#102421",
    accent: "#1F7A6B",
    card: "#FFFFFF",
  },
  {
    id: "cobalt",
    label: "Cobalt",
    background: "#F4F6FB",
    text: "#12182B",
    accent: "#2F5DFF",
    card: "#FFFFFF",
  },
  {
    id: "lilac",
    label: "Lilac",
    background: "#F6F3F8",
    text: "#241A33",
    accent: "#6C4AB6",
    card: "#FFFFFF",
  },
  {
    id: "night",
    label: "Night",
    background: "#1C2B4A",
    text: "#F7F1E5",
    accent: "#7FDBDA",
    card: "#243656",
  },
  {
    id: "cream",
    label: "Cream",
    background: "#F6F1E8",
    text: "#141414",
    accent: "#6B2430",
    card: "#FFFFFF",
  },
  {
    id: "blush",
    label: "Blush",
    background: "#F3D6D0",
    text: "#3A1C22",
    accent: "#6B2430",
    card: "#FFF8F6",
  },
  {
    id: "newsprint",
    label: "Newsprint",
    background: "#F4F1EA",
    text: "#1A1A1A",
    accent: "#C45C26",
    card: "#FFFFFF",
  },
  {
    id: "midnight",
    label: "Midnight",
    background: "#0E1320",
    text: "#F4F1EA",
    accent: "#E8B86D",
    card: "#1A2233",
  },
  {
    id: "sand",
    label: "Sand",
    background: "#E7D7C1",
    text: "#2C2416",
    accent: "#8C5A3C",
    card: "#F7F1E8",
  },
  {
    id: "coral",
    label: "Coral",
    background: "#FFE8E0",
    text: "#2A1614",
    accent: "#FF6B4A",
    card: "#FFFFFF",
  },
  {
    id: "forest",
    label: "Forest",
    background: "#E7F0E4",
    text: "#142018",
    accent: "#1F6B3A",
    card: "#F7FBF6",
  },
  {
    id: "electric",
    label: "Electric",
    background: "#F3F0FF",
    text: "#1A1230",
    accent: "#6D4AFF",
    card: "#FFFFFF",
  },
  {
    id: "mono",
    label: "Mono",
    background: "#F7F7F5",
    text: "#111111",
    accent: "#111111",
    card: "#FFFFFF",
  },
];
